language: ruby
cache:
  - bundler
  - yarn
sudo: false
rvm:
  - 2.3

bundler_args: --without development

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - ./bin/webpack

