language: ruby
cache:
  - bundler
  - yarn
sudo: false
rvm:
  - 2.6.6

node_js:
  - 15


bundler_args: "--without development"

services:
  - postgresql

before_script:
  - nvm install node  
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - yarn install --ignore-engines
  - yarn --version
  - node --version
  - "./bin/webpack"

deploy:
  provider: heroku
  app: yac-budget
  on: master
  api_key:
    secure: J6Rewej+xTGeC7/2Nc4BAGqBSRdEELfqP7x2wr6ShAQOSfrAJwZ/TEinZMPGJms2g3CfLn7jHqq9VFsn9O7ctVIvBVaiCJizTjif84sqZxwSpxjyAz4YEQx+sraq1C1PpWjtYTD7toln0AVuvPqA05wPfSfl+0kjdflg7OOswF9zufNaU8Ir6T8LdMyaV3LYhVsIlJ9ziWBBNWZs4qmSQOHmWCmeEevWQV2tlII6kMFw9Fj3ugk/VIWgdLpDyCBDFoUqt8/2PgBOPRHw3NISWjwUtdyPApT0vPNx1jeBkcOd202lHL9nOcP+U4HPmMkmje1CFueC0X934qBa3XpvQccgD/bnSUAaXjBYwhhlNwMcKmIyflGWnlHq1a84V2iypybYWes464mjCE0Mm/8mDzoNxnAuuFpvKhBV7sUZdsNANa0XIJddoDeCzWCWYNKLwfPfu3ThTcxzEqC9crPdZ7Q4jFLAz1EBKwgbRTBFdnL+opjjClKciDGKvIpCshLjFwmJm4hkgiys0e9PXeG9djqv/BiLvPHUkjLTcFzYJ6L6QilhmPEL+WB8UvRJXtff3K0cosBN5W+30snlLNxF4G6rDbo3FXdiL0rV96lVPV436ptWa6IA10T2xxh6GYXquOVf7vogEP0QYVq++5/J5VtgMBIKJHBgOMVg3kFgFsk=
  run: "rake db:migrate"
  skip_cleanup: true
