language: ruby
cache:
  - bundler
  - yarn
sudo: false
rvm:
  - 2.4

bundler_args: "--without development"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - yarn install --ignore-engines
  - "./bin/webpack"

deploy:
  provider: heroku
  app: yac-budget
  on: master
  api_key:
    secure: JrLWa4GBwLSKUtnUpB9wWdXg+ZPbMe4aNfZz7V/yWyeuAUAsVREyvXZAFR5lyCquRavFk1wXw72DWth1xG66taH02i0hHF+345OC/hw2iIrVqBKmP3sVmVQD/VQCBFfD3Avw5nhC8SorQxd01XxG1ZjMmHWh+/SJ98kJLOcurWUOFJR4Yau1crHQwNeOPXwn5Ci931QNw3tTcPmZnfBaKxHLKo7udmetJ+BNA5k7ZaxAoc1qnap3n18ZCIUO2zS29uureH7w4YBfpldea/GWdQjxT5TvWEAeJRojr33rU85uuYLUgbSbbVjXPpHHXJbju0SBf4QpSbN+e3WepVTBNYB0W6yiiCziXdK9ftK9Y4kBUlFGEiCcOGp0iVrpOzND6AWUEjYmEO3N1xwpmrWaCVAEnlfxc45DV9a3mwHN2KlQRL9SsztuoTVo4zBPDfkwl8Q4Fy95pMY6eH8cuH9UgnGAtVa0XbHzYvO302Ot2NqVJOxfXuPl0ZNLvBjAOupaQH+rbnZdcY7VQVHz4TMIC/l68ivVYxtIA3/i3xtqgH9vAn14y/FAK0481fXNU5kceaJWdjpLfGgNNNO6QJuUUuxBJX/fgXXXrPXw6IRb42HJg3S8XCJ/3FH9f03A/2Nue1oAAkRXoaqHZM5jehRTikIETM7O+LzygAz7UWRffKI=
  run: "rake db:migrate"
  skip_cleanup: true
