language: ruby
cache:
  - bundler
  - yarn
sudo: false
rvm:
  - 2.4

bundler_args: "--without development"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - yarn install
  - "./bin/webpack"

deploy:
  provider: heroku
  app: yac-budget
  on: master
  api_key:
    secure: PS824at3lNwsx6rgVxEs/iNG/5XoJmOTP4ejAss9SEzN9qaBwfvkCVFcwQFqJUZcVV0d4N2lFmgKoKutKBYDvB9cKh3UBrrrmC4b8TofVjfUGEvKmhIbwy25OfyZapznr6lphmil7zpv65gxd77B//n+lxPl/e2dyi4k5n56yu1ez1riJT16bJ6nB2nZmMWucX/JAQm2pi6mdzA526MjBlHPABjYfShBBQdcLpo23FmqITxcbjMVdSR9Gcim1U+rVj7nYIJEirLB/WRyjMpwukaG0y89JFDHQorQj9lA4k6Ak7E4l2/akZALcAfq+fvhS0P6BoHQcVZUMVRhHVKo5jnSNKG/vbSJQ4NBQcS1GDTq8S7oR+aGQmZ2DeL0AESWuR+piUV/Jfaer5MgHRnek2dNjU7103zsqGLOlD0S0RTkqOaiw9yhHBxkkTTOY7QDjgWp4MCcGaIJU/JgQ/faioMo71htUiDUVl5AjJ8zZWZBuxhJpmc6w2C72Yo/cVoR10DdlDBkJU79zFbLhEqEuAhy2sfkvtYeZAgfIMxdmddd9DwGLpfnA4p2J3nYGrRnLT5KXCpBqP/ULVxBmR3F6Amc/APBbMCWyNmbZ5vLSHmUlUN8At/Jtd9XksTrzI5mzHdh25dZKhOrFa7O/pnIMvTBqgmbHv2phOkeAe1hpR8=
  run: "rake db:migrate"
  skip_cleanup: true
