language: ruby
cache:
  - bundler
  - yarn
sudo: false
rvm:
  - 2.6.6

bundler_args: "--without development"

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - yarn install --ignore-engines
  - "./bin/webpack"

deploy:
  provider: heroku
  app: yac-budget
  on: master
  api_key:
    secure: i6cDd5UeYB0y2M595+XscyeUBqUa3SQG3Ak1I3E6tpfI7amkinZR8Ax4WcNdBXH01cZsKpmL9yswm50ciYXEd+SvpMWqmsxLocjxVRqW94uVqn7Ry9S3pyFByYE+sIeEJQ/IUdTjqNWnby7h7QpXnuqDDaot+O5wgQxktrlQyu03Ct29iKOHwgo38Xru7sKyqHbKQFJvHMlBw+rVPkEyJlfAobYvqxF3sObHC9JZJVnhK733csy1yOGA8bA7ZATkf4zhuqS614vzIjGW38qli6v1ZLRHZc7R9U0fuFkNuMrO9XB6dY2eTmwxhFuG4Mfx8kxb5oMTq5tqgtKuzp4HYwdghuuW7hvocmAs7jciRGap0dKpX8GNroBNVsVVWVyhRF8KkVyGvP9EYtEf+yI+ERR1p6yuoegQHrrp0kpKNiH34UGwg9owIHewCXIIVXqGQ/0KeMqw43PfOw4A6PAktAb98QjCN/UEhWA4G+UTNSF8ZKAZkSwX1BswgXl29iJpDAtdjXx4bHeKwkDewK/Br6X1ktyWT9CBSkrMyVfhC9tZS7wcft0FXpz+DOnFvSz+8CFMHTL4uHFqJtG8xFkm5zOrePOvygK7JXCkUkk6xbKFtQfCvWR2u4ue+Gqk4V/hxGdjVbayyS4yUFP8aFxFxPYXPNSPrRLQa85uMGux7Qk=
  run: "rake db:migrate"
  skip_cleanup: true
