language: ruby
cache:
  - bundler
  - yarn
sudo: false
rvm:
  - 2.6.6

node_js:
  - 15


bundler_args: "--without development"

services:
  - postgresql

before_script:
  - nvm install node  
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - yarn install --ignore-engines
  - yarn --version
  - node --version
  - "./bin/webpack"

deploy:
  provider: heroku
  app: yac-budget
  on: master
  api_key:
    secure: T7TJQU8d+LrXoGRPX8/BLDyiorTpS/XCoQmHTOst7yGZWrykl1QdaeRzjbJE03TCbVyxJN3xzK8+Bj3qHFIxIYR+wVenKgcZefoxK5iYbRe8gZuqlbXvxQdkawgxavfkmJFjHUS8hwhtct6Tx19cNZ+jXVKWwhImZerdHfG1PjbaqfIB6zVnB0KdA9tsMWtoD66a+uTtwT1BxHXP9WWugFjFmXv658FNKEXThNk5Ef12BmwQt2mv6TzappdZZdysR4WDBlXIZrcy/pbAs0TyUYPFPiQYLc1Ea+KZeMVGvHHX0+OE3e6N4tPz87aNiAM42l19qn1bfmeP+P7FkX3VKuHbRP4Nuz+OpaiAXqq3CgYU38yW+8pAC+ZpINXCEUGyWbrMXwlJFqmjf68uOsGF+pQtD6sM5CMalypJWpFQqcJIJJoXpRR/QDx0fa1THq2Fb8Pia93qHNtLAOhSoQcn2/BjU2gRQGigSTjRI+H47VNm9SY2EBGZkMv2RHMKhlpCkf7QiOhG7M75fY9TWzY+ROvbWAU6sAYwMxMpApHrUGTv3EIvam3mY/vrN/LwLloqATVOM+mFBGg03tAOGaGDEf58G1xJqI7+ONDEnKorQu/aRQf0YKXqEDesphZI8hh9Y2yR7R4B+3Kd7lwKF6YndE6EnmTforiKleyWZQdhoi8=
  run: "rake db:migrate"
  skip_cleanup: true
