# fly.toml app configuration file generated for budget-application on 2023-09-16T10:17:00-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "budget-application"
primary_region = "sea"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    BUNDLER_VERSION = "2.1.4"
    NODE_VERSION = "20"
    RUBY_VERSION = "3.0.4"
[deploy]
  release_command = "bundle exec rails db:migrate"

[env]
  PORT = "8080"
  SERVER_COMMAND = "bundle exec puma -C config/puma.rb"

[processes]
  web = "bin/rails s"
  cron = "cron -f"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["web"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
