:scheduler:
  :schedule:
    process_daily_recurring_transactions:
      cron: '0 0 * * * *'   # Runs once a day
      class: Recurring::DailyJob
    process_weekly_recurring_transactions:
      cron: '0 1 * * MON'   # Runs every monday
      class: Recurring::WeeklyJob
    process_monthly_recurring_transactions:
      cron: '0 2 1 * *'   # Runs once a month
      class: Recurring::MonthlyJob
    process_yearly_recurring_transactions:
      cron: '0 3 1 1 *'   # Runs once a year
      class: Recurring::YearlyJob