require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe RecurringTransactionsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # RecurringTransaction. As you add validations to RecurringTransaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    build(:recurring_transaction, account: create(:account, user: @user)).attributes
  }

  let(:invalid_attributes) {
    build(:recurring_transaction_invalid).attributes
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RecurringTransactionsController. Be sure to keep this updated too.
  let(:valid_session) {{}}

  before :each do
    @user = create(:user)
    sign_in @user
  end

  describe 'GET #index' do
    it 'returns a success response' do
      valid_attributes[:user_id] = @user.id
      recurring_transaction = RecurringTransaction.create! valid_attributes
      get :index, params: {account_id: recurring_transaction.account.id}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #show' do
    it 'returns a success response' do
      valid_attributes[:user_id] = @user.id
      recurring_transaction = RecurringTransaction.create! valid_attributes
      get :show, params: {id: recurring_transaction.to_param, account_id: recurring_transaction.account.id}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #new' do
    it 'returns a success response' do
      account = create(:account, user: @user)
      get :new, params: {account_id: account.id}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'GET #edit' do
    it 'returns a success response' do
      valid_attributes[:user_id] = @user.id
      recurring_transaction = RecurringTransaction.create! valid_attributes
      get :edit, params: {id: recurring_transaction.to_param, account_id: recurring_transaction.account.id}, session: valid_session
      expect(response).to be_success
    end
  end

  describe 'POST #create' do
    context 'with valid params' do
      it 'creates a new RecurringTransaction' do
        account = create(:account, user: @user)
        expect {
          post :create, params: {recurring_transaction: valid_attributes, account_id: account.id}, session: valid_session
        }.to change(RecurringTransaction, :count).by(1)
      end

      it 'redirects to the account' do
        account = create(:account, user: @user)
        post :create, params: {recurring_transaction: valid_attributes, account_id: account.id}, session: valid_session
        expect(response).to redirect_to(RecurringTransaction.last.account)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'new' template)" do
        account = create(:account, user: @user)
        post :create, params: {recurring_transaction: invalid_attributes, account_id: account.id}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'PUT #update' do
    context 'with valid params' do
      let(:new_attributes) {
        {name: 'new_name'}
      }

      it 'updates the requested recurring_transaction' do
        account = create(:account, user: @user)
        recurring_transaction = RecurringTransaction.create! valid_attributes
        put :update, params: {id: recurring_transaction.to_param, recurring_transaction: new_attributes, account_id: account.id}, session: valid_session
        recurring_transaction.reload
        expect(recurring_transaction.name).to eq('new_name')
      end

      it 'redirects to the account' do
        account = create(:account, user: @user)
        recurring_transaction = RecurringTransaction.create! valid_attributes
        put :update, params: {id: recurring_transaction.to_param, recurring_transaction: valid_attributes, account_id: account.id}, session: valid_session
        expect(response).to redirect_to(recurring_transaction.account)
      end
    end

    context 'with invalid params' do
      it "returns a success response (i.e. to display the 'edit' template)" do
        recurring_transaction = RecurringTransaction.create! valid_attributes
        put :update, params: {id: recurring_transaction.to_param, recurring_transaction: invalid_attributes, account_id: recurring_transaction.account.id}, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe 'DELETE #destroy' do
    it 'destroys the requested recurring_transaction' do
      account = create(:account, user: @user)
      recurring_transaction = RecurringTransaction.create! valid_attributes
      expect {
        delete :destroy, params: {id: recurring_transaction.to_param, account_id: account.id}, session: valid_session
      }.to change(RecurringTransaction, :count).by(-1)
    end

    it 'redirects to the account recurring transaction list ' do
      recurring_transaction = RecurringTransaction.create! valid_attributes
      delete :destroy, params: {id: recurring_transaction.to_param, account_id: recurring_transaction.account.id}, session: valid_session
      expect(response).to redirect_to(account_recurring_transactions_path(recurring_transaction.account))
    end
  end

end
