name: "Build and deploy"
on:
  push:
    branches: [ master ]
jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
  deploy:
    needs:
      - run-tests
    uses: ./.github/workflows/deploy.yml
    secrets:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}