name: Deploy to Heroku
on:
  workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      DATABASE_URL: "postgres://budget:budget@localhost:5432/budget-application_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to Heroku container
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      # Add or replace database setup steps here
      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a appname yac-budget
      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release -a appname yac-budget
      - name: Rails migration
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku run rake db:migrate