name: Deploy to Heroku
on:
  workflow_call:
    secrets:
      HEROKU_API_KEY:
        required: true
      HEROKU_EMAIL:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      DATABASE_URL: "postgres://budget:budget@localhost:5432/budget-application_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Heroku credentials
        run: |
          cat > ~/.netrc <<EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
            machine git.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_API_KEY
          EOF
          echo $HEROKU_EMAIL
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      - name: Create remote
        run: heroku git:remote -a yac-budget
      - name: Deploy
        run: git push heroku main
      - name: Rails migration
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku run rake db:migrate