name: Run tests
on:
  workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: budget-application_test
          POSTGRES_USER: budget
          POSTGRES_PASSWORD: budget
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://budget:budget@localhost:5432/budget-application_test"
    strategy:
      matrix:
        node-version: [ 15.x ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      - name: Set up database schema
        run: |
          bundle exec rake db:migrate
          bundle exec rake db:test:load
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Install yarn dependencies
        run: |
          npm -g install yarn
          yarn install --ignore-engines
          yarn --version
          node --version
      - name: Compile assets
        run: RAILS_ENV=production bundle exec rake assets:precompile
      # Add or replace test runners here
      - name: Run tests
        run: bundle exec rspec spec